spring:
  application:
    name: HospitalSystem-Interface
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/design_HospitalDB?serverTimezone=Asia/Shanghai
    username: root
    password: 991234
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
        server-addr: localhost:8848
      discovery:
        server-addr: localhost:8848
  data:
    redis:
      host: 127.0.0.1
      database: 0
      port: 6379
      password:
  cache:
    type: redis

server:
  port: 8080
