spring:
  application:
    name: HospitalSystem-Admin
  cloud:
    loadbalancer:
      nacos:
        enabled: true
    nacos:
      config:
        import-check:
          enabled: false
      discovery:
        server-addr: localhost:8848
server:
  port: 8003

